name: desafio_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #FIREBASE
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19

  #MOBX
  mobx: ^2.0.7+2
  flutter_mobx: ^2.0.6+1
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7

  #API
  dio: ^4.0.6

  #MAPS
  google_maps_flutter: ^2.1.7

  #UX/UI
  flutter_svg: ^1.1.0
  google_fonts: ^3.0.1

  #OUTRAS
  shared_preferences: ^2.0.15
  another_flushbar: ^1.10.29
  flutter_native_splash: ^2.2.3

flutter_native_splash:
  color: "#7052CC"
  image: assets/splash.png
  android_gravity: center
  android: true
  android12: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
